### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by maplesyrupdev** [FiratUsta/Chromora#1]
Nice simple application. I like it.

You could consider defaulting the colour to the value in the  html input id="hex" instead of setting a default in the javascript.

  let initColor;
  //      if(theme === "dark"){
  //          initColor = new Color().fromHEX("#E7B03A");
  //      }else{
            //initColor = new Color().fromHEX("#2265A4");
			_colorInput("hex");
	//		;
       // }
        //updateColors(initColor);
        //ColorWheel.positionFromHSV(initColor);
        _generate();

Also, it would be nice to be able to copy each colour from the generated palette in text.

**Comment by PrimaryCat** [comment]
Apologies for the late response, I haven't touched this project in a long while.

I'm going to look into the first idea to see if the actual implementation will be better. From my initial understanding of your suggestion, I agree that defaulting to the hex input field might be a more elegant solution but I'm not sure if it'd make things faster or less complicated. Since I use two different default colors for light and dark modes, I feel like I need to set them in JS anyway? Let me know if I'm misunderstanding something about your suggestion or I'm missing some obvious solution.

I like the second idea a lot, I'm starting to work on this feature straight away.

**Comment by PrimaryCat** [comment]
I think with the coming 1.4.0 update, some refactoring of the code will need to be done in any case. So I will most likely need to add a function that encompasses the first suggestion.

I'm also opening a new issue for the second suggestion at #3, this will be added in the new update.

I'm closing this issue, if you have any suggestions on how to implement the second suggestion, you're always welcome to share your opinions on the new topic.
